### ISSUE TITLE
Feedback on Moonlight Bakery Website

### ISSUE THREAD

**Issue by jhartley1412** [ramseykjenna/Moonlight-Bakery-Website#1]
I really like how clean and easy to traverse through this site is. With how pretty everything is, I almost wish that there were hover effects over the buttons (the learn more, view, etc). I also agree that the drop shadow on the map is a little strong. I remember you saying that it felt too flat without it, and maybe you could see how it would look on the dark grey-blue box containing it; it'll give the whole map element a sense of popping out, but the map itself will look more in place.

Also small design/text note, on the header, the lorum ipsum "Truffaut DIY keffiyeh, twee messenger bag venmo locavore organic master cleanse marfa gochujang selvage" watch out for orphan words (the "selvage" is on a line of it's own). You can usually fix that with letter spacing or kerning, or changing the width size of the parent container.

With the menu page, I like the idea of left aligning the food items (you can put each group of items in their own container and give them a max-width to keep them from taking up the whole page when you expand the browser), and the line in between the pastries section is a little confusing.

**Comment by scottanderson5** [comment]
I agree with Janina, I was going to suggest left-aligning the food items on the menu page. 

I would maybe think of throwing some different typography in there. What you have seems very uniform. There may be some fun ones to experiment with that don't detract from the overall theme of the page.

**Comment by ramseykjenna** [comment]
Thanks for the feedback guys!! Yeah I definitely need to put in some work on the menu page!!
